### PR TITLE
Allow creation of HTTPS shortlink URLs

### PR DESCRIPTION
**Pull request by alanhogan**
⚠️  Adds a new config constant. Carefully update your `config.php` to match. _Update: Or don’t. Lessn More will do the right thing anyway_

If you are running Lessn More on an HTTPS domain, this will make newly created URLs also match HTTPS.

~@dosch Try this out, maybe, and see if it works? Careful, I haven't even run this code yet.~ _Update: Fixed. Works for me!_

### CODE REVIEW

**Comment by dosch** [comment]
@alanhogan thnx for the swift changes. I overwrote my index.php file with your and copy /pasted the changes you made in config-example.php to my config.php.

Sadly not change. shortened urls are created, but when used result in 404. Like http://frph.nl/d

**Comment by alanhogan** [comment]
I am not so sure that it is a lessn more error. It looks like as server configuration problem. In the case of Apache, the .htaccess file should be redirecting that URL internally to Lessn More, but that 404 page looks generic to me, not like a Lessn More 404 page. I’m not sure if you are on Apache at a glance. Also some hosts might disable htaccess files.

**Comment by dosch** [comment]
Hey @alanhogan, I am on Apache and I can create/modify htaccess files on my shared hosting.
I'd be happy to try some code if you could tell me what to put in there. Thank you!

**Comment by dosch** [comment]
reinstalled Lessnmore.
Uri's created with this branch are now having a leadin `1` instead of `http` or `https`. 
Like: `1://mydomain.com/a`

Adding `https:` to line 38 in index.php does add `https` to the url again, but does not remove the `1`

`define('BCURLS_URL', 	str_replace('-/index.php', '', BCURLS_PROTOCOL.'**https**://'.BCURLS_DOMAIN.$_SERVER['PHP_SELF']));`

**Comment by alanhogan** [comment]
Heh... oh, PHP… it’s been a while since I've written much of it. As I mentioned, I didn't run this code myself yet. I will take a closer look but clearly I messed up the new BCURLS_PROTOCOL logic

**Comment by alanhogan** [comment]
@dosch I have fixed the stupid bug that led to URLs like `1://mydomain.me/5`. I forgot how PHP evaluates boolean expressions. Fixed now. Works for me™, with and without the constant defined in `config.php`. Just update `/-/index.php` to match this PR!

**Pull request merged**
